name: Build and test
description: The action file for building and testing a .NET project.
author: a.eiji

runs:
  using: 'composite'
  steps:
    - name: set up dotnet core sdk
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
         
    - name: restoring dependencies
      run: dotnet restore --no-cache
      shell: bash
    
    - name: build project
      run: dotnet build --no-restore --configuration Release
      shell: bash

    - name: Run tests
      run: |
        dotnet test --no-build --verbosity normal \
          --collect:"XPlat Code Coverage" \
          -r ./TestResults \
          --logger "trx;LogFileName=test_results.trx"
      shell: bash

    - name: Report coverage
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator "-reports:./TestResults/**/coverage.cobertura.xml" "-targetdir:./TestResults/CoverageReport" -reporttypes:Html
        
      shell: bash