name: build and test

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  BuildAndTest:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: nuget restore
        run: dotnet restore --no-cache
        
      - name: build
        run: dotnet build --no-restore --configuration Release
      
      - name: run tests
        run: dotnet test -c Release --no-restore --verbosity normal
      